# *QuantNbody* tutorials : first steps with the package

**Dr. Saad Yalouz - Laboratoire de Chimie Quantique de Strasbourg, France - July 2022**


 

## Philosophy of the package

The philosophy of the **QuantNBody** package is to facilitate the implementation and the manipulation of quantum many-body systems composed of electrons or bosons. To reach this goal, the package has been designed to provide a quick and easy way to build many-body operators and wavefunctions in a given many-body basis. This way it becomes possible to get access in a few python lines to quantities/objects of interest for research and method developements.





To proceed, the package works with two fundamental ingredients.

A) The first is the **creation of a reference many-body basis** (based on a total number of quantum particles and modes/orbitals to fill) in which every operator can be represented.

B) The second is the creation of the set of **hopping operators $a^\dagger  a$** which are necessary to build any particle-number conserving many-body operator. 

Once these two ingredients
have been created, the user can employ pre-built functions in order to  construct various type of many-body
operators (e.g. hamiltonians, spin operators), and manipulate/visualize quantum many-body states. Note that
the QuantNBody package has been also designed to provide flexibility to the users so that they can also create their
own operators and functions based on the tools already implemented in the code.

**Nota Bene:** For sake of simplicity, we will only focus in these tutorials on fermionic systems. 

## First things first, let us import the package !

In [1]:
import quantnbody as qnb   # <==== General import 

import numpy as np

##  Building a many-body basis

To build a many-body basis for a fermionic system, the QuantNBody package generates a list of many-body states which describe the repartition of $N_{elec}$ electrons in $2N_{MO}$ spin-orbitals. These states are numerically referenced by a list of kappa indices such that

$$
\Big\lbrace |\kappa \rangle \Big\rbrace_{\textstyle \kappa=1}^{\textstyle \dim_H}
$$ 
 
The dimension $\dim_H$ of the many-body basis depends on the number of electron $N_{elec}$ and spatial orbital $N_{MO}$ via a binomial law such that

$$\dim_H = \binom{2N_{MO}}{N_{elec}}$$

**A little example with $N_{MO}=N_{elec}=2$ :** In this case, we should have **6 many-body states.**

In [15]:
N_MO = N_elec = 2 # We define the numebr of MO adn electrons

nbody_basis = qnb.fermionic.tools.build_nbody_basis( N_MO, N_elec ) # Building the nbody_basis

print('Shape  of the kappa states')
for s in range(len(nbody_basis)):
    print('| kappa={} >'.format(s), '=', nbody_basis[s])

Shape  of the kappa states
| kappa=0 > = [1 1 0 0]
| kappa=1 > = [1 0 1 0]
| kappa=2 > = [1 0 0 1]
| kappa=3 > = [0 1 1 0]
| kappa=4 > = [0 1 0 1]
| kappa=5 > = [0 0 1 1]


**What is the meaning of these six bit strings ?** 

Here, each bit string represents a many-body state. As an example, let us check the first state for which we have
    
$$| \kappa  = 0\rangle = | \underbrace{   \overbrace{1}^{ \textstyle  {\alpha}}, \; \; \;\overbrace{1}^{ \textstyle  {\beta}},}_{\textstyle 1st \ MO}\; \; \underbrace{\overbrace{0}^{ \textstyle  {\alpha}}, \; \; \; \overbrace{0}^{ \textstyle  {\beta}}}_{\textstyle 2nd \ MO} \rangle$$

Here we choose to structure the occupation numbers as follows

- Each couple of terms refer to **a same spatial orbital**
- **Even** indices refer to **$\alpha$-spinorbitals**  
- **Odd** indices refer to **$\beta$-spinorbitals**  


**IMPORTANT NOTE :**

For each configuration, we associate a unique $\kappa$ index associated to a genuine numerical vector. In practice, any numerical representation of a given many-body operator is numerically given in the basis of $\kappa$. As an example, let us imagine we want to encode numerically a second quantization operator $O$. This means in practice that we create a matrix representation in the many-body basis such that

$$ O = \sum_{\kappa, \kappa' 
 =1}^{\dim_H}  \langle \kappa' | O | \kappa  \rangle  \; | \kappa'    \rangle\langle \kappa |  $$

This work is realized by the QuantNBody package to build every operators we need to descrbie a many-body system.

##  Building and storing the $a^\dagger_{p,\sigma} a_{q,\tau}$ operators

Once the list of many-body state is obtained, in the **QuantNBody** package a crucial point consist in building the $a^\dagger_{p,\sigma} a_{q,\tau}$ many-body operators. 

In practice, these operators play a central role in many cases of study as soon as we have to deal with **systems that conserves its total number of particles.** In this case, one can show that many objects (i.e. excitation operators, spin operators, reduced density matrices ...) are built in practice using series of $a^\dagger_{p,\sigma} a_{q,\tau}$ operators.

With the QuantNBody package, we build these operators once and for all and store them via a very simple command line. This way we will be able to use them  later on for any type of developments.

The command line is simple and only require the list of many-body state we built previously :

In [3]:
a_dagger_a = qnb.fermionic.tools.build_operator_a_dagger_a( nbody_basis )

**How to get access to these operators once stored ?**

The way each operator is stored follows the way we order the spin-orbitals in our many-body states. As illustrative examles, taking the following elements will return the associated many-body operators :

<center>  a_dagger_a[0,0]  $ \longrightarrow a^\dagger_{0,\alpha} a_{0,\alpha}$ </center>

<center>  a_dagger_a[1,0]  $ \longrightarrow a^\dagger_{0,\beta} a_{0,\alpha}$ </center>

<center>  a_dagger_a[10,1]  $ \longrightarrow a^\dagger_{5,\alpha} a_{0,\beta}$ </center>

In practice, the resulting many-body operators we get access to are expressed in the original many-body basis stored under a sparse format. We take the example of the first operator  $  a^\dagger_{0,\alpha} a_{0,\alpha}$ below for which we show the asscociated sparse and dense matrix representation in the many-body basis

In [4]:
print(  "Sparse representation of a_dagger_a[0,0]" )
print( a_dagger_a[0,0] )

print( )
print( "Dense representation of a_dagger_a[0,0]" )
print( a_dagger_a[0,0].A )

Sparse representation of a_dagger_a[0,0]
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0

Dense representation of a_dagger_a[0,0]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


We see here that this operator simpy counts the number of electrons in the first spin-orbital explaining why we only have ones on the three first elements of the diagonal (see the shape of the three many-body states given ealrier to understand)


## Building our first many-body Hamiltonian : fermi-Hubbard molecule 

In this final part of the tutorial we will use the previously built a_dagger_a variable to implement a fermi-Hubbard molecule. In the local site basis, the model Hamiltonian is usually expressed such that:

$$ 
\hat{H} = \color{blue}{\sum_{\langle i,j \rangle}^{N_{MO}} -t_{ij} \sum_{\sigma=\uparrow,\downarrow} (\hat{a}^\dagger_{j,\sigma}\hat{a}_{i,\sigma}+\hat{a}^\dagger_{i,\sigma}\hat{a}_{j,\sigma})} 
+ \color{red}{\sum_i^{N_{MO}} \mu_{ii} \sum_{\sigma=\uparrow,\downarrow} \hat{a}^\dagger_{i,\sigma}\hat{a}_{i,\sigma} }
+ \color{black}{
\sum_i^{N_{MO}} U_{iiii} \hat{a}^\dagger_{i,\uparrow}\hat{a}_{i,\uparrow} \hat{a}^\dagger_{i,\downarrow}\hat{a}_{i,\downarrow} 
}
$$

with :
- <font color='blue'> $t_{ij}$ the hopping terms between the pair of connected sites $\langle i, j \rangle$.  
- <font color='red'> $\mu_{ii}$ the local chemical potential on site "$i$".
- <font color='black'> $U_{iiii}$ the local coulombic repulsion on site "$i$".
    
    We illustrate the shape of the system below
 
    <img src="graph.png" width="400"  style="margin:auto"/>
    
 In a more general basis (not necessarily local) we have
$$   
\hat{H} =\sum_{\langle p,q \rangle}^{N_{MO}} -h_{pq} \sum_{\sigma=\uparrow,\downarrow} (\hat{a}^\dagger_{p,\sigma}\hat{a}_{q,\sigma}+\hat{a}^\dagger_{q,\sigma}\hat{a}_{p,\sigma}) + \sum_i^{N_{MO}} U_{p,q,r,s} \hat{a}^\dagger_{p,\uparrow}\hat{a}_{q,\uparrow} \hat{a}^\dagger_{r,\downarrow}\hat{a}_{s,\downarrow} 
 $$
where for commodity we have introduced the one-body integral term $h_{pq}$ which embed the hopping terms and the chemical potentials such as
$$
h_{pq} = \sum_{i,j}^{N_{MO}} (-t_{ij} + \delta_{ij}\mu_{ii}) C_{i,p} C_{j,q} 
$$
and the "delocalized version" of the coulombic repulsion term
$$
U_{pqrs} = \sum_{i}^{N_{MO}}  U_{i,i,i,i} C_{i,p} C_{i,q} C_{i,r} C_{i,s}
$$
where the matrix ${\bf C}$ encodes the Molecular Orbital coefficient if we want for example to express the Hamiltonian in a delocalized basis.



**Building the Hamiltonian :** To initiate construction of the matrix representation of the operator in the many-body basis, we first define the hopping between the sites $t$, the chemical potentials $\mu$ and the electronic repulsion $U$.

In [5]:
# Setup for the simulation ========
N_MO   = N_elec = 2  
t_  = np.zeros((N_MO,N_MO))
U_  = np.zeros((N_MO,N_MO,N_MO,N_MO))
Mu_ = np.zeros((N_MO,N_MO)) 
for i in range(N_MO): 
    U_[i,i,i,i]  =  1 * (1+i)  # Local coulombic repulsion 
    Mu_[i,i]     = -1 * (1+i)  # Local chemical potential
    
    for j in range(i+1,N_MO): 
        t_[i,j] = t_[j,i] = - 1  # hopping

h_ = t_  + np.diag( np.diag(Mu_) ) # Global one-body matrix = hoppings + chemical potentials

print( 't_=\n',t_ ,'\n')

print( 'Mu_=\n',Mu_ ,'\n')

print( 'h_=\n',h_ ,'\n')

t_=
 [[ 0. -1.]
 [-1.  0.]] 

Mu_=
 [[-1.  0.]
 [ 0. -2.]] 

h_=
 [[-1. -1.]
 [-1. -2.]] 



To build the Hamiltonian, we simply have to pass three ingredients to the an already built function:
- Parameters of the model
- The Many-body basis
- The $a^\dagger a $ operators

as shown below

In [6]:
H_fermi_hubbard = qnb.fermionic.tools.build_hamiltonian_fermi_hubbard( h_,
                                                                       U_,
                                                                       nbody_basis,
                                                                       a_dagger_a )

Similarily to the $a^\dagger_{p,\sigma} a_{q,\sigma} $ operator, the Hamiltonian $H$ is represented in the many-body basis with a native sparse representation (which can be made dense):

In [7]:
print('H (SPARSE) =' )
print(H_fermi_hubbard)

print()
print('H (DENSE) =' )
print(H_fermi_hubbard.A)

H (SPARSE) =
  (0, 0)	-1.0
  (0, 2)	-1.0
  (0, 3)	1.0
  (1, 1)	-3.0
  (2, 0)	-1.0
  (2, 2)	-3.0
  (2, 5)	-1.0
  (3, 0)	1.0
  (3, 3)	-3.0
  (3, 5)	1.0
  (4, 4)	-3.0
  (5, 2)	-1.0
  (5, 3)	1.0
  (5, 5)	-2.0

H (DENSE) =
[[-1.  0. -1.  1.  0.  0.]
 [ 0. -3.  0.  0.  0.  0.]
 [-1.  0. -3.  0.  0. -1.]
 [ 1.  0.  0. -3.  0.  1.]
 [ 0.  0.  0.  0. -3.  0.]
 [ 0.  0. -1.  1.  0. -2.]]


Once $H$ is built, we can diagonalize the resulting matrix.

In [8]:
eig_energies, eig_vectors =  np.linalg.eigh(H_fermi_hubbard.A)

print('Energies =', eig_energies[:4] )

Energies = [-4.41421356 -3.         -3.         -3.        ]


And finally, we can call a very usefull function from the QuantNBody package that help visualizing the shape of a  wavefunction as shown below. This function lists the most important many-body state contributing to the wavefunction with the associated coefficients in front.

In [9]:
WFT_to_analyse = eig_vectors[:,0]

# Visualizing the groundstate in the many-body basis
qnb.fermionic.tools.visualize_wft( WFT_to_analyse, nbody_basis ) # <=== FCT IN THE PACKAGE
print()


	-----------
	 Coeff.      N-body state
	-------     -------------
	-0.57454	|0110⟩
	+0.57454	|1001⟩
	+0.47596	|0011⟩
	+0.33656	|1100⟩


